### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by fntsrlike** [fntsrlike/slack-irc-plugin#10]
Sometimes will happened
![2015-02-11 3 59 55](https://cloud.githubusercontent.com/assets/2680724/6143633/246edde0-b207-11e4-8937-51c5f0eb4e9f.png)

**Comment by hinet60613** [comment]
https://github.com/martynsmith/node-irc/issues/331
Seems that the bug is caused from node module `irc`

**Comment by fntsrlike** [comment]
It has been fixed with new version of node-irc (>=0.3.12).
https://github.com/martynsmith/node-irc/pull/318
