### ISSUE TITLE
'irc-colors' is not included in 'irc' with npm 2.6.0

### ISSUE THREAD

**Issue by fkztw** [fntsrlike/slack-irc-plugin#11]
the result of `$ npm ls`

```
├─┬ irc@0.3.9
│ ├── ansi-color@0.2.1
│ ├─┬ iconv@2.1.6
│ │ └── nan@1.6.2
│ └── node-icu-charset-detector@0.0.7
```

on FreeBSD 10.1-RELEASE with npm version 2.6.0

I added "irc-colors": "~1.1.0" to the dependencies of package.json and redid the `npm install` to solve this problem.

**Comment by fkztw** [comment]
uh...
`$ npm update` can solve my problem.
don't need to add  'irc-colors' into the dependencies of package.json because 'irc' module indeed write 'irc-colors' as a dependency.

**Comment by fntsrlike** [comment]
Thanks for report. I will add `$npm update` to install steps to prevent this issue.
