### ISSUE TITLE
Add `/me` command sync

### ISSUE THREAD

**Issue by fntsrlike** [fntsrlike/slack-irc-plugin#2]
Add `/me` command sync from both to each other

**Comment by davy-tw** [comment]
There is no `/me` API on Slack even if you can heard `/me` from IRC.

**Comment by fntsrlike** [comment]
Yes, you are right.
![2015-02-04 2 30 55](https://cloud.githubusercontent.com/assets/2680724/6036100/d5f87978-ac7a-11e4-8a8e-031c26331f54.png)

In other way, we can listen `/me` events from IRC, and output text with Italics. Then we have the same display.
![2015-02-04 2 32 05](https://cloud.githubusercontent.com/assets/2680724/6036101/d620a75e-ac7a-11e4-8d8d-3fa8b0188d15.png)

**Comment by fkztw** [comment]
ref to this PR https://github.com/fntsrlike/slack-irc-syncbot/pull/13

**Comment by davy-tw** [comment]
why not add the effect in IrcMsgEncoder ?

**Comment by fkztw** [comment]
you mean like this?
https://github.com/NCTU-NBA/slack-irc-plugin/commit/7419fc9aee906c086e011d5c92d4ce3f58c07453

**Comment by fntsrlike** [comment]
BTW, Maybe we can use `slash command` interaction to listen `/me` from slack, and sent message to IRC

**Comment by fkztw** [comment]
add the effect in IrcMsgEncoder.
ref to PR https://github.com/fntsrlike/slack-irc-syncbot/pull/15

**Comment by fkztw** [comment]
Slash Commands API won't send Slash Commands which are overlapped with those default Slash Commands like `/me`.
Even if you have already set `/me` into the Slash Commands API to listen on, Slack still sends it via outgoing token not slash commands token.
Other commands which are not overlapped with default slash commands are ok to be sent via the slash commands token.
