### ISSUE TITLE
Getting "<Not string type message>"

### ISSUE THREAD

**Issue by victorbrca** [fntsrlike/slack-irc-plugin#24]
I have configured everything and one way integration works (IRC => Slack), however the other way (Slack => IRC) is not working. Messages are coming with "<Not string type message>" on the IRC channel. 

I can see the messages without a problem on the server's output. 

`[DEBUG] Got type error message：[whatever was typed in Slack]`

Thanks.

**Comment by fntsrlike** [comment]
I am preparing oral defense of master's degree on July. After that I will keep maintaining this project. Thanks for your report. = )

**Comment by ExeQ** [comment]
Hi,
the problem is line 8 in slack-msg-decoder.js
it should be:
`if (typeof message == "string") {`
not:
`if (typeof this.message == "string") {`

**Comment by fntsrlike** [comment]
Thanks @M157q . 
I am service on substitute military service of Taiwan. It's too busy to maintain project immediately. Orz

**Comment by fkztw** [comment]
https://github.com/fntsrlike/slack-irc-syncbot/pull/22/commits/18d8540a7b42a8e04c5644c61b7e3908d3cea1a2
Looks like this bug had already been solved at the develop branch. XD

**Comment by fntsrlike** [comment]
XDDDDDD
